/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as StarmapImport } from "./routes/starmap";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const StarmapRoute = StarmapImport.update({
  id: "/starmap",
  path: "/starmap",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/starmap": {
      id: "/starmap";
      path: "/starmap";
      fullPath: "/starmap";
      preLoaderRoute: typeof StarmapImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/starmap": typeof StarmapRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/starmap": typeof StarmapRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/starmap": typeof StarmapRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/starmap";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/starmap";
  id: "__root__" | "/" | "/starmap";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  StarmapRoute: typeof StarmapRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StarmapRoute: StarmapRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/starmap"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/starmap": {
      "filePath": "starmap.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
